### ISSUE TITLE
[Request] Example in readme

### ISSUE THREAD

**Issue by FGRibreau** [jeffbski/autoflow-graphviz#1]
Could it be possible to see some generated graphs (with their react equivalent) directly from the README.

That way we could more easily grasp and react-graphviz is all about without having to install it.

Thanks !

[Update] Oh ok, I just discovered this one https://github.com/jeffbski/react/raw/master/doc/simple.png

**Comment by mnm364** [comment]
bump?

**Comment by jeffbski** [comment]
@mnm364 I added an example graphic. However note that I am no longer actively working on this or autoflow projects, but contributors are welcome if development is needed. I've updated the README to mention this and autoflow.
